add domain_code fallback
freifunkMUC/uisp_respondd pull request #2
Opened 2023-07-26 15:16 UTC by T0biii

add domain_code "ffmuc_uisp_respondd_fallback" 
there is no domain, or?

2023-07-26 18:45 UTC, GoliathLabs approved these changes

2024-01-03 17:36 UTC, grische commented
@T0biii I think this PR is not sufficient for it to work. I added a new PR #3 that should work.

2024-01-03 17:39 UTC, grische requested changes
@T0biii I think this PR is not sufficient for it to work. I added a new PR https://github.com/freifunkMUC/uisp_respondd/pull/3 that addresses these as I had no push rights on your repo

2024-01-03 17:39 UTC, grische commented on uisp_respondd/uisp_client.py
> +    domain_code: str
AFAICT there some changes in respondd_client.py missing.

2024-01-03 17:53 UTC, T0biii commented
see #3

2024-01-03 17:53 UTC, closed without merging